name: bandit
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths:
      - mlflow_oidc_auth/**

jobs:
  main:
    name: Run bandit
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: PyCQA/bandit-action@v1.0.1
        with:
          severity: high
          confidence: high
